import { Providers } from "./providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Rakuten Rations",
  description: "Generated by create next app",
  icons: [{ rel: 'icon', url: "/categoryImages/saigai_hozonsyoku.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <>{children}</>
        </Providers>
      </body>
    </html>
  );
}
