@startuml
hide empty members

entity Organization {
    * name : String
    num : int 
    woman_ratio : int
    stored_foods : Stored_food[]
}

entity Stored_food {
    id : String
    category : String
    num : int
    expired_at : DateTime
    org? : Organization
    # org_name : String
    * (id, expired_at)
}

Organization --o{ Stored_food : org_name is foreign key

@enduml